# Generated by Django 4.2.6 on 2023-10-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Бишкек', max_length=255)),
                ('timezone', models.CharField(default='GMT+6', max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, default=42.87, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=74.59, max_digits=9)),
            ],
        ),
    ]
