# Generated by Django 4.2.6 on 2023-10-10 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='status',
        ),
        migrations.AddField(
            model_name='todotask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todotask',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todotask',
            name='title',
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todotask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
