# Generated by Django 4.2.6 on 2023-10-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_todotask_status_todotask_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastingrecord',
            name='made_up_days',
        ),
        migrations.RemoveField(
            model_name='fastingrecord',
            name='missed_days',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='prayer_time',
        ),
        migrations.AddField(
            model_name='fastingrecord',
            name='fasted',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
